import Img from "../../assets/Image 11.png";
import Img2 from '../../assets/Image 46.png'


interface Book {
  id: number;
  title: string;
  author: string;
  price: number;
  image: string;
  image2:string;
  originalPrice: number;
  rating: number;
  reviews: number;
  outOfStock: boolean;
}

export const books: Book[] = [
  {
    id: 1,
    title: "Don't Make Me Think",
    author: "Steve Krug",
    price: 1500,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 2,
    title: "Lean UX",
    author: "Jeff Gothelf",
    price: 1800,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: true,
  },
  {
    id: 3,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
  {
    id: 4,
    title: "Direct Manipulation",
    author: "Bret Victor",
    price: 2000,
    image: Img,
    image2:Img2,
    originalPrice: 2000,
    rating: 4.5,
    reviews: 20,
    outOfStock: false,
  },
];
